import { Product } from "@/types";

export const products: Product[] = [
    {
      id: "1",
      name: "Product 1",
      company: "Company 1",
      category: "Category 1",
      price: 100,
      rating: 4.5,
      discount: 10,
      availability: "yes",
      imageSrc: "/computer.jpg",
    },
    {
      id: "2",
      name: "Product 2",
      company: "Company 2",
      category: "Category 2",
      price: 200,
      rating: 3.5,
      discount: 20,
      availability: "out-of-stock",
      imageSrc: "/computer.jpg",
    },
    {
      id: "3",
      name: "Product 3",
      company: "Company 3",
      category: "Category 3",
      price: 300,
      rating: 4.0,
      discount: 15,
      availability: "yes",
      imageSrc: "/computer.jpg",
    },
    {
      id: "4",
      name: "Product 4",
      company: "Company 4",
      category: "Category 4",
      price: 400,
      rating: 5.0,
      discount: 25,
      availability: "yes",
      imageSrc: "/computer.jpg",
    },
    {
      id: "5",
      name: "Product 5",
      company: "Company 5",
      category: "Category 5",
      price: 500,
      rating: 4.5,
      discount: 30,
      availability: "out-of-stock",
      imageSrc: "/computer.jpg",
    },
    {
      id: "6",
      name: "Product 6",
      company: "Company 6",
      category: "Category 6",
      price: 600,
      rating: 3.0,
      discount: 35,
      availability: "yes",
      imageSrc: "/computer.jpg",
    }
  ];